-- =============================================================================
-- APEXRIDE — RECORDED MIGRATION HISTORY
-- Migration: 20260928140000_apexride_ddl
--
-- GENERATED FILE. Do not edit by hand.
-- Generated by: npm run migration:write  (src/db/write-migration.ts)
-- Source of truth: src/db/migrate.ts -> DDL_STATEMENTS
--
-- This file is a history ARTIFACT. The authoritative schema is
-- src/db/migrate.ts, executed with `npm run migrate`. prisma/schema.prisma
-- cannot express CHECK constraints, partial unique indexes, or triggers, so
-- `prisma migrate dev` would emit DDL that drops them; do not run it here.
--
-- This database is baselined by `npm run migrate`, so this migration is
-- registered with `prisma migrate resolve --applied` instead of being replayed
-- against a database that already contains these objects.
--
-- Contains the full ApexRide DDL: 4 enums, 6 tables, 3 partial unique indexes
-- (idx_rider_single_active_trip, idx_driver_single_active_trip,
-- idx_driver_single_active_vehicle), 4 CHECK constraints
-- (check_trip_driver_required_when_assigned, check_fare_non_negative,
-- check_fare_ledger_balances, check_rating_1_to_5), and the trigger
-- trg_review_completed_trip_only with fn_review_completed_trip_only().
-- The live catalog is verified in evidence/ddl-inventory.txt.
-- ========================================================================== */

-- >>> generated below from DDL_STATEMENTS <<<

DO $$ BEGIN
      CREATE TYPE "DriverStatus" AS ENUM ('offline', 'available', 'busy', 'suspended');
    EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
      CREATE TYPE "VehicleTier" AS ENUM ('standard', 'comfort', 'xl');
    EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
      CREATE TYPE "TripStatus" AS ENUM ('requested', 'driver_assigned', 'driver_arriving', 'in_progress', 'completed', 'cancelled_by_rider', 'cancelled_by_driver');
    EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
      CREATE TYPE "PaymentStatus" AS ENUM ('pending', 'succeeded', 'failed', 'refunded');
    EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS "Rider" (
      "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      "fullName" VARCHAR(100) NOT NULL,
      "email" VARCHAR(255) UNIQUE NOT NULL,
      "phoneNumber" VARCHAR(20) UNIQUE NOT NULL,
      "rating" DECIMAL(3, 2) NOT NULL DEFAULT 5.00,
      "isActive" BOOLEAN NOT NULL DEFAULT true,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "deletedAt" TIMESTAMPTZ
    );

CREATE INDEX IF NOT EXISTS "idx_rider_email" ON "Rider"("email");

CREATE INDEX IF NOT EXISTS "idx_rider_phone" ON "Rider"("phoneNumber");

CREATE TABLE IF NOT EXISTS "Driver" (
      "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      "fullName" VARCHAR(100) NOT NULL,
      "email" VARCHAR(255) UNIQUE NOT NULL,
      "phoneNumber" VARCHAR(20) UNIQUE NOT NULL,
      "licenseNumber" VARCHAR(50) UNIQUE NOT NULL,
      "status" "DriverStatus" NOT NULL DEFAULT 'offline',
      "rating" DECIMAL(3, 2) NOT NULL DEFAULT 5.00,
      "totalTrips" INTEGER NOT NULL DEFAULT 0,
      "currentLat" DOUBLE PRECISION,
      "currentLng" DOUBLE PRECISION,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "deletedAt" TIMESTAMPTZ
    );

CREATE INDEX IF NOT EXISTS "idx_driver_status_geo" ON "Driver"("status", "currentLat", "currentLng");

CREATE INDEX IF NOT EXISTS "idx_driver_email" ON "Driver"("email");

CREATE TABLE IF NOT EXISTS "Vehicle" (
      "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      "driverId" UUID NOT NULL REFERENCES "Driver"("id") ON DELETE CASCADE,
      "make" VARCHAR(50) NOT NULL,
      "model" VARCHAR(50) NOT NULL,
      "year" INTEGER NOT NULL,
      "licensePlate" VARCHAR(20) UNIQUE NOT NULL,
      "tier" "VehicleTier" NOT NULL DEFAULT 'standard',
      "color" VARCHAR(30) NOT NULL,
      "isActive" BOOLEAN NOT NULL DEFAULT true,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

CREATE INDEX IF NOT EXISTS "idx_vehicle_driver" ON "Vehicle"("driverId", "isActive");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_driver_single_active_vehicle"
    ON "Vehicle"("driverId")
    WHERE "isActive";

CREATE TABLE IF NOT EXISTS "Trip" (
      "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      "riderId" UUID NOT NULL REFERENCES "Rider"("id") ON DELETE RESTRICT,
      "driverId" UUID REFERENCES "Driver"("id") ON DELETE RESTRICT,
      "vehicleId" UUID REFERENCES "Vehicle"("id") ON DELETE SET NULL,
      "status" "TripStatus" NOT NULL DEFAULT 'requested',
      "pickupLat" DOUBLE PRECISION NOT NULL,
      "pickupLng" DOUBLE PRECISION NOT NULL,
      "pickupAddress" TEXT NOT NULL,
      "dropoffLat" DOUBLE PRECISION NOT NULL,
      "dropoffLng" DOUBLE PRECISION NOT NULL,
      "dropoffAddress" TEXT NOT NULL,
      "distanceMeters" INTEGER,
      "durationSeconds" INTEGER,
      "driverNameSnapshot" VARCHAR(100),
      "driverPhoneSnapshot" VARCHAR(20),
      "vehiclePlateSnapshot" VARCHAR(20),
      "vehicleModelSnapshot" VARCHAR(100),
      "requestedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "acceptedAt" TIMESTAMPTZ,
      "startedAt" TIMESTAMPTZ,
      "completedAt" TIMESTAMPTZ,
      "cancelledAt" TIMESTAMPTZ,
      "cancellationReason" TEXT,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

CREATE INDEX IF NOT EXISTS "idx_trip_rider_status" ON "Trip"("riderId", "status");

CREATE INDEX IF NOT EXISTS "idx_trip_driver_status" ON "Trip"("driverId", "status");

CREATE INDEX IF NOT EXISTS "idx_trip_status_requestedAt" ON "Trip"("status", "requestedAt");

CREATE INDEX IF NOT EXISTS "idx_trip_rider_completed" ON "Trip"("riderId", "completedAt" DESC);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_rider_single_active_trip"
    ON "Trip"("riderId")
    WHERE status IN ('requested', 'driver_assigned', 'driver_arriving', 'in_progress');

CREATE UNIQUE INDEX IF NOT EXISTS "idx_driver_single_active_trip"
    ON "Trip"("driverId")
    WHERE status IN ('driver_assigned', 'driver_arriving', 'in_progress');

DO $$ BEGIN
      ALTER TABLE "Trip"
      ADD CONSTRAINT "check_trip_driver_required_when_assigned"
      CHECK (
        "status" NOT IN ('driver_assigned', 'driver_arriving', 'in_progress', 'completed')
        OR "driverId" IS NOT NULL
      );
    EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS "FareReceipt" (
      "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      "tripId" UUID UNIQUE NOT NULL REFERENCES "Trip"("id") ON DELETE RESTRICT,
      "baseFareMinor" INTEGER NOT NULL,
      "distanceFareMinor" INTEGER NOT NULL,
      "timeFareMinor" INTEGER NOT NULL,
      "surgeMultiplier" DECIMAL(3, 2) NOT NULL DEFAULT 1.00,
      "subtotalMinor" INTEGER NOT NULL,
      "discountMinor" INTEGER NOT NULL DEFAULT 0,
      "totalFareMinor" INTEGER NOT NULL,
      "platformFeeMinor" INTEGER NOT NULL,
      "driverEarningsMinor" INTEGER NOT NULL,
      "currency" VARCHAR(3) NOT NULL DEFAULT 'NGN',
      "paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'pending',
      "paymentMethod" VARCHAR(50),
      "paymentReference" VARCHAR(100),
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

ALTER TABLE "FareReceipt" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$ BEGIN
      ALTER TABLE "FareReceipt"
      ADD CONSTRAINT "check_fare_non_negative"
      CHECK ("totalFareMinor" >= 0 AND "driverEarningsMinor" >= 0);
    EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
      ALTER TABLE "FareReceipt"
      ADD CONSTRAINT "check_fare_ledger_balances"
      CHECK ("totalFareMinor" = "platformFeeMinor" + "driverEarningsMinor");
    EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS "Review" (
      "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      "tripId" UUID UNIQUE NOT NULL REFERENCES "Trip"("id") ON DELETE RESTRICT,
      "riderId" UUID NOT NULL REFERENCES "Rider"("id") ON DELETE RESTRICT,
      "driverId" UUID NOT NULL REFERENCES "Driver"("id") ON DELETE RESTRICT,
      "rating" INTEGER NOT NULL,
      "comment" TEXT,
      "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();

DO $$ BEGIN
      ALTER TABLE "Review"
      ADD CONSTRAINT "check_rating_1_to_5"
      CHECK (rating >= 1 AND rating <= 5);
    EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE OR REPLACE FUNCTION "fn_review_completed_trip_only"() RETURNS trigger
    LANGUAGE plpgsql AS $fn$
    DECLARE
      v_status "TripStatus";
    BEGIN
      SELECT t."status" INTO v_status FROM "Trip" t WHERE t."id" = NEW."tripId";

      IF FOUND AND v_status IS DISTINCT FROM 'completed'::"TripStatus" THEN
        RAISE EXCEPTION
          'check_review_completed_trip_only: trip % is in status "%"; only completed trips may be reviewed',
          NEW."tripId", v_status
          USING
            ERRCODE = 'check_violation',
            CONSTRAINT = 'check_review_completed_trip_only';
      END IF;

      RETURN NEW;
    END;
    $fn$;

DROP TRIGGER IF EXISTS "trg_review_completed_trip_only" ON "Review";

CREATE TRIGGER "trg_review_completed_trip_only"
    BEFORE INSERT OR UPDATE OF "tripId" ON "Review"
    FOR EACH ROW EXECUTE FUNCTION "fn_review_completed_trip_only"();

CREATE INDEX IF NOT EXISTS "idx_review_driver_rating" ON "Review"("driverId", "rating");

CREATE INDEX IF NOT EXISTS "idx_review_rider" ON "Review"("riderId");
