/* =============================================================================
 * Generates prisma/migrations/<name>/migration.sql FROM src/db/migrate.ts.
 *
 * The generated SQL is a byte-for-byte copy of the DDL_STATEMENTS array that
 * `npm run migrate` executes. It is written, never hand edited, so the recorded
 * migration history can never drift from the authoritative schema.
 *
 * Because the database is baselined by `npm run migrate` (not by
 * `prisma migrate deploy`), the generated migration is registered with
 * `prisma migrate resolve --applied` rather than replayed. See README.md.
 *
 * Usage: npm run migration:write
 * ========================================================================== */

import fs from "fs";
import path from "path";
import { DDL_STATEMENTS } from "./migrate.js";

/** Must sort after any migration already recorded in _prisma_migrations. */
export const MIGRATION_NAME = "20260928140000_apexride_ddl";

const ROOT = process.cwd();
const MIGRATIONS_DIR = path.join(ROOT, "prisma", "migrations");
const TARGET_DIR = path.join(MIGRATIONS_DIR, MIGRATION_NAME);

const HEADER = `-- =============================================================================
-- APEXRIDE — RECORDED MIGRATION HISTORY
-- Migration: ${MIGRATION_NAME}
--
-- GENERATED FILE. Do not edit by hand.
-- Generated by: npm run migration:write  (src/db/write-migration.ts)
-- Source of truth: src/db/migrate.ts -> DDL_STATEMENTS
--
-- This file is a history ARTIFACT. The authoritative schema is
-- src/db/migrate.ts, executed with \`npm run migrate\`. prisma/schema.prisma
-- cannot express CHECK constraints, partial unique indexes, or triggers, so
-- \`prisma migrate dev\` would emit DDL that drops them; do not run it here.
--
-- This database is baselined by \`npm run migrate\`, so this migration is
-- registered with \`prisma migrate resolve --applied\` instead of being replayed
-- against a database that already contains these objects.
--
-- Contains the full ApexRide DDL: 4 enums, 6 tables, 3 partial unique indexes
-- (idx_rider_single_active_trip, idx_driver_single_active_trip,
-- idx_driver_single_active_vehicle), 4 CHECK constraints
-- (check_trip_driver_required_when_assigned, check_fare_non_negative,
-- check_fare_ledger_balances, check_rating_1_to_5), and the trigger
-- trg_review_completed_trip_only with fn_review_completed_trip_only().
-- The live catalog is verified in evidence/ddl-inventory.txt.
-- ========================================================================== */

-- >>> generated below from DDL_STATEMENTS <<<

`;

export function writeMigrationHistory(): string {
  const sqlPath = path.join(TARGET_DIR, "migration.sql");
  const lockPath = path.join(MIGRATIONS_DIR, "migration_lock.toml");

  fs.mkdirSync(TARGET_DIR, { recursive: true });
  fs.writeFileSync(sqlPath, HEADER + DDL_STATEMENTS.join("\n\n") + "\n", "utf8");
  fs.writeFileSync(
    lockPath,
    `# Please do not edit this file manually\n# It should be added in your version-control system (e.g. Git)\nprovider = "postgresql"\n`,
    "utf8"
  );

  return sqlPath;
}

if (process.argv[1] && process.argv[1].endsWith("write-migration.ts")) {
  const written = writeMigrationHistory();
  console.log(
    `Wrote ${DDL_STATEMENTS.length} DDL statements to ${path.relative(ROOT, written)}`
  );
  console.log(`Wrote ${path.relative(ROOT, path.join(MIGRATIONS_DIR, "migration_lock.toml"))}`);
  console.log(
    `Register it against the baselined database with:\n  npx prisma migrate resolve --applied ${MIGRATION_NAME}`
  );
}
